"""empty message

Revision ID: 1d2008757f3
Revises: 2ac485420e60
Create Date: 2015-08-10 04:36:09.876000

"""

# revision identifiers, used by Alembic.
revision = '1d2008757f3'
down_revision = '2ac485420e60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_guests_name', table_name='guests')
    op.create_index(op.f('ix_guests_name'), 'guests', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guests_name'), table_name='guests')
    op.create_index('ix_guests_name', 'guests', ['name'], unique=1)
    ### end Alembic commands ###
